public with sharing class Constant {
    public static final String ACC_RECORD_TYPE_NAME = 'Donor';
    public static final String OPP_RECORD_TYPE_NAME = 'Donation';
    public static final String CAMP_RECORD_TYPE_NAME = 'Donation Campaign';
    public static final String CAMP_OBJ_NAME = 'campaign';
    public static final String EXPIRED_STATUS = 'Expired';
    public static final String ACTIVE_STATUS = 'Active';
    public static final String PLEDGED_STATUS = 'Pledged';
    public static final String CAMPAIGN_NAME = 'Name';
    
}

